tesla <- read.csv("./data/tesla.csv")
toyota <- read.csv("./data/toyota.csv")
ford <- read.csv("./data/ford.csv")
honda <- read.csv("./data/honda.csv")
bmw <- read.csv("./data/bmw.csv")
mercedes <- read.csv("./data/mercedes.csv")
subaru <- read.csv("./data/subaru.csv")
suzuki <- read.csv("./data/suzuki.csv")
gmc <- read.csv("./data/gmc.csv")
volkswagen <- read.csv("./data/volkswagen.csv")
porsche <- read.csv("./data/porsche.csv")
rollsRoyce <- read.csv("./data/rolls-royce.csv")
ferrari <- read.csv("./data/ferrari.csv")
volvo <- read.csv("./data/volvo.csv")
renault <- read.csv("./data/renault.csv")
nissan <- read.csv("./data/nissan.csv")
mazda <- read.csv("./data/mazda.csv")
isuzu <- read.csv("./data/isuzu.csv")

#-----------------------------------------------------------------------------#

tesla$Date <- rev(tesla$Date)
tesla$Close.Last <- rev(tesla$Close.Last)
tesla$Volume <- rev(tesla$Volume)
tesla$Open <- rev(tesla$Open)
tesla$High <- rev(tesla$High)
tesla$Low <- rev(tesla$Low)

toyota$Date <- rev(toyota$Date)
toyota$Close.Last <- rev(toyota$Close.Last)
toyota$Volume <- rev(toyota$Volume)
toyota$Open <- rev(toyota$Open)
toyota$High <- rev(toyota$High)
toyota$Low <- rev(toyota$Low)

ford$Date <- rev(ford$Date)
ford$Close.Last <- rev(ford$Close.Last)
ford$Volume <- rev(ford$Volume)
ford$Open <- rev(ford$Open)
ford$High <- rev(ford$High)
ford$Low <- rev(ford$Low)

honda$Date <- rev(honda$Date)
honda$Close.Last <- rev(honda$Close.Last)
honda$Volume <- rev(honda$Volume)
honda$Open <- rev(honda$Open)
honda$High <- rev(honda$High)
honda$Low <- rev(honda$Low)

bmw$Date <- rev(bmw$Date)
bmw$Close.Last <- rev(bmw$Close.Last)
bmw$Volume <- rev(bmw$Volume)
bmw$Open <- rev(bmw$Open)
bmw$High <- rev(bmw$High)
bmw$Low <- rev(bmw$Low)

mercedes$Date <- rev(mercedes$Date)
mercedes$Close.Last <- rev(mercedes$Close.Last)
mercedes$Volume <- rev(mercedes$Volume)
mercedes$Open <- rev(mercedes$Open)
mercedes$High <- rev(mercedes$High)
mercedes$Low <- rev(mercedes$Low)

subaru$Date <- rev(subaru$Date)
subaru$Close.Last <- rev(subaru$Close.Last)
subaru$Volume <- rev(subaru$Volume)
subaru$Open <- rev(subaru$Open)
subaru$High <- rev(subaru$High)
subaru$Low <- rev(subaru$Low)

suzuki$Date <- rev(suzuki$Date)
suzuki$Close.Last <- rev(suzuki$Close.Last)
suzuki$Volume <- rev(suzuki$Volume)
suzuki$Open <- rev(suzuki$Open)
suzuki$High <- rev(suzuki$High)
suzuki$Low <- rev(suzuki$Low)

gmc$Date <- rev(gmc$Date)
gmc$Close.Last <- rev(gmc$Close.Last)
gmc$Volume <- rev(gmc$Volume)
gmc$Open <- rev(gmc$Open)
gmc$High <- rev(gmc$High)
gmc$Low <- rev(gmc$Low)

volkswagen$Date <- rev(volkswagen$Date)
volkswagen$Close.Last <- rev(volkswagen$Close.Last)
volkswagen$Volume <- rev(volkswagen$Volume)
volkswagen$Open <- rev(volkswagen$Open)
volkswagen$High <- rev(volkswagen$High)
volkswagen$Low <- rev(volkswagen$Low)

porsche$Date <- rev(porsche$Date)
porsche$Close.Last <- rev(porsche$Close.Last)
porsche$Volume <- rev(porsche$Volume)
porsche$Open <- rev(porsche$Open)
porsche$High <- rev(porsche$High)
porsche$Low <- rev(porsche$Low)

rollsRoyce$Date <- rev(rollsRoyce$Date)
rollsRoyce$Close.Last <- rev(rollsRoyce$Close.Last)
rollsRoyce$Volume <- rev(rollsRoyce$Volume)
rollsRoyce$Open <- rev(rollsRoyce$Open)
rollsRoyce$High <- rev(rollsRoyce$High)
rollsRoyce$Low <- rev(rollsRoyce$Low)

ferrari$Date <- rev(ferrari$Date)
ferrari$Close.Last <- rev(ferrari$Close.Last)
ferrari$Volume <- rev(ferrari$Volume)
ferrari$Open <- rev(ferrari$Open)
ferrari$High <- rev(ferrari$High)
ferrari$Low <- rev(ferrari$Low)

volvo$Date <- rev(volvo$Date)
volvo$Close.Last <- rev(volvo$Close.Last)
volvo$Volume <- rev(volvo$Volume)
volvo$Open <- rev(volvo$Open)
volvo$High <- rev(volvo$High)
volvo$Low <- rev(volvo$Low)

renault$Date <- rev(renault$Date)
renault$Close.Last <- rev(renault$Close.Last)
renault$Volume <- rev(renault$Volume)
renault$Open <- rev(renault$Open)
renault$High <- rev(renault$High)
renault$Low <- rev(renault$Low)

nissan$Date <- rev(nissan$Date)
nissan$Close.Last <- rev(nissan$Close.Last)
nissan$Volume <- rev(nissan$Volume)
nissan$Open <- rev(nissan$Open)
nissan$High <- rev(nissan$High)
nissan$Low <- rev(nissan$Low)

mazda$Date <- rev(mazda$Date)
mazda$Close.Last <- rev(mazda$Close.Last)
mazda$Volume <- rev(mazda$Volume)
mazda$Open <- rev(mazda$Open)
mazda$High <- rev(mazda$High)
mazda$Low <- rev(mazda$Low)

isuzu$Date <- rev(isuzu$Date)
isuzu$Close.Last <- rev(isuzu$Close.Last)
isuzu$Volume <- rev(isuzu$Volume)
isuzu$Open <- rev(isuzu$Open)
isuzu$High <- rev(isuzu$High)
isuzu$Low <- rev(isuzu$Low)

#-----------------------------------------------------------------------------#

tesla$Date <- as.Date(tesla$Date, format="%m/%d/%Y")
tesla$Close.Last <- substr(tesla$Close.Last, 2, 6)
tesla$Close.Last = as.double(tesla$Close.Last)
tesla$Open <- substr(tesla$Open, 2, 6)
tesla$Open = as.double(tesla$Open)
tesla$High <- substr(tesla$High, 2, 6)
tesla$High = as.double(tesla$High)
tesla$Low <- substr(tesla$Low, 2, 6)
tesla$Low = as.double(tesla$Low)

toyota$Date <- as.Date(toyota$Date, format="%m/%d/%Y")
toyota$Close.Last <- substr(toyota$Close.Last, 2, 6)
toyota$Close.Last = as.double(toyota$Close.Last)
toyota$Open <- substr(toyota$Open, 2, 6)
toyota$Open = as.double(toyota$Open)
toyota$High <- substr(toyota$High, 2, 6)
toyota$High = as.double(toyota$High)
toyota$Low <- substr(toyota$Low, 2, 6)
toyota$Low = as.double(toyota$Low)

ford$Date <- as.Date(ford$Date, format="%m/%d/%Y")
ford$Close.Last <- substr(ford$Close.Last, 2, 6)
ford$Close.Last = as.double(ford$Close.Last)
ford$Open <- substr(ford$Open, 2, 6)
ford$Open = as.double(ford$Open)
ford$High <- substr(ford$High, 2, 6)
ford$High = as.double(ford$High)
ford$Low <- substr(ford$Low, 2, 6)
ford$Low = as.double(ford$Low)

honda$Date <- as.Date(honda$Date, format="%m/%d/%Y")
honda$Close.Last <- substr(honda$Close.Last, 2, 6)
honda$Close.Last = as.double(honda$Close.Last)
honda$Open <- substr(honda$Open, 2, 6)
honda$Open = as.double(honda$Open)
honda$High <- substr(honda$High, 2, 6)
honda$High = as.double(honda$High)
honda$Low <- substr(honda$Low, 2, 6)
honda$Low = as.double(honda$Low)

bmw$Date <- as.Date(bmw$Date, format="%m/%d/%Y")
bmw$Close.Last <- substr(bmw$Close.Last, 2, 6)
bmw$Close.Last = as.double(bmw$Close.Last)
bmw$Open <- substr(bmw$Open, 2, 6)
bmw$Open = as.double(bmw$Open)
bmw$High <- substr(bmw$High, 2, 6)
bmw$High = as.double(bmw$High)
bmw$Low <- substr(bmw$Low, 2, 6)
bmw$Low = as.double(bmw$Low)

mercedes$Date <- as.Date(mercedes$Date, format="%m/%d/%Y")
mercedes$Close.Last <- substr(mercedes$Close.Last, 2, 6)
mercedes$Close.Last = as.double(mercedes$Close.Last)
mercedes$Open <- substr(mercedes$Open, 2, 6)
mercedes$Open = as.double(mercedes$Open)
mercedes$High <- substr(mercedes$High, 2, 6)
mercedes$High = as.double(mercedes$High)
mercedes$Low <- substr(mercedes$Low, 2, 6)
mercedes$Low = as.double(mercedes$Low)

subaru$Date <- as.Date(subaru$Date, format="%m/%d/%Y")
subaru$Close.Last <- substr(subaru$Close.Last, 2, 6)
subaru$Close.Last = as.double(subaru$Close.Last)
subaru$Open <- substr(subaru$Open, 2, 6)
subaru$Open = as.double(subaru$Open)
subaru$High <- substr(subaru$High, 2, 6)
subaru$High = as.double(subaru$High)
subaru$Low <- substr(subaru$Low, 2, 6)
subaru$Low = as.double(subaru$Low)

suzuki$Date <- as.Date(suzuki$Date, format="%m/%d/%Y")
suzuki$Close.Last <- substr(suzuki$Close.Last, 2, 6)
suzuki$Close.Last = as.double(suzuki$Close.Last)
suzuki$Open <- substr(suzuki$Open, 2, 6)
suzuki$Open = as.double(suzuki$Open)
suzuki$High <- substr(suzuki$High, 2, 6)
suzuki$High = as.double(suzuki$High)
suzuki$Low <- substr(suzuki$Low, 2, 6)
suzuki$Low = as.double(suzuki$Low)

gmc$Date <- as.Date(gmc$Date, format="%m/%d/%Y")
gmc$Close.Last <- substr(gmc$Close.Last, 2, 6)
gmc$Close.Last = as.double(gmc$Close.Last)
gmc$Open <- substr(gmc$Open, 2, 6)
gmc$Open = as.double(gmc$Open)
gmc$High <- substr(gmc$High, 2, 6)
gmc$High = as.double(gmc$High)
gmc$Low <- substr(gmc$Low, 2, 6)
gmc$Low = as.double(gmc$Low)

volkswagen$Date <- as.Date(volkswagen$Date, format="%m/%d/%Y")
volkswagen$Close.Last <- substr(volkswagen$Close.Last, 2, 6)
volkswagen$Close.Last = as.double(volkswagen$Close.Last)
volkswagen$Open <- substr(volkswagen$Open, 2, 6)
volkswagen$Open = as.double(volkswagen$Open)
volkswagen$High <- substr(volkswagen$High, 2, 6)
volkswagen$High = as.double(volkswagen$High)
volkswagen$Low <- substr(volkswagen$Low, 2, 6)
volkswagen$Low = as.double(volkswagen$Low)

porsche$Date <- as.Date(porsche$Date, format="%m/%d/%Y")
porsche$Close.Last <- substr(porsche$Close.Last, 2, 6)
porsche$Close.Last = as.double(porsche$Close.Last)
porsche$Open <- substr(porsche$Open, 2, 6)
porsche$Open = as.double(porsche$Open)
porsche$High <- substr(porsche$High, 2, 6)
porsche$High = as.double(porsche$High)
porsche$Low <- substr(porsche$Low, 2, 6)
porsche$Low = as.double(porsche$Low)

rollsRoyce$Date <- as.Date(rollsRoyce$Date, format="%m/%d/%Y")
rollsRoyce$Close.Last <- substr(rollsRoyce$Close.Last, 2, 6)
rollsRoyce$Close.Last = as.double(rollsRoyce$Close.Last)
rollsRoyce$Open <- substr(rollsRoyce$Open, 2, 6)
rollsRoyce$Open = as.double(rollsRoyce$Open)
rollsRoyce$High <- substr(rollsRoyce$High, 2, 6)
rollsRoyce$High = as.double(rollsRoyce$High)
rollsRoyce$Low <- substr(rollsRoyce$Low, 2, 6)
rollsRoyce$Low = as.double(rollsRoyce$Low)

ferrari$Date <- as.Date(ferrari$Date, format="%m/%d/%Y")
ferrari$Close.Last <- substr(ferrari$Close.Last, 2, 6)
ferrari$Close.Last = as.double(ferrari$Close.Last)
ferrari$Open <- substr(ferrari$Open, 2, 6)
ferrari$Open = as.double(ferrari$Open)
ferrari$High <- substr(ferrari$High, 2, 6)
ferrari$High = as.double(ferrari$High)
ferrari$Low <- substr(ferrari$Low, 2, 6)
ferrari$Low = as.double(ferrari$Low)

volvo$Date <- as.Date(volvo$Date, format="%m/%d/%Y")
volvo$Close.Last <- substr(volvo$Close.Last, 2, 6)
volvo$Close.Last = as.double(volvo$Close.Last)
volvo$Open <- substr(volvo$Open, 2, 6)
volvo$Open = as.double(volvo$Open)
volvo$High <- substr(volvo$High, 2, 6)
volvo$High = as.double(volvo$High)
volvo$Low <- substr(volvo$Low, 2, 6)
volvo$Low = as.double(volvo$Low)

renault$Date <- as.Date(renault$Date, format="%m/%d/%Y")
renault$Close.Last <- substr(renault$Close.Last, 2, 6)
renault$Close.Last = as.double(renault$Close.Last)
renault$Open <- substr(renault$Open, 2, 6)
renault$Open = as.double(renault$Open)
renault$High <- substr(renault$High, 2, 6)
renault$High = as.double(renault$High)
renault$Low <- substr(renault$Low, 2, 6)
renault$Low = as.double(renault$Low)

nissan$Date <- as.Date(nissan$Date, format="%m/%d/%Y")
nissan$Close.Last <- substr(nissan$Close.Last, 2, 6)
nissan$Close.Last = as.double(nissan$Close.Last)
nissan$Open <- substr(nissan$Open, 2, 6)
nissan$Open = as.double(nissan$Open)
nissan$High <- substr(nissan$High, 2, 6)
nissan$High = as.double(nissan$High)
nissan$Low <- substr(nissan$Low, 2, 6)
nissan$Low = as.double(nissan$Low)

mazda$Date <- as.Date(mazda$Date, format="%m/%d/%Y")
mazda$Close.Last <- substr(mazda$Close.Last, 2, 6)
mazda$Close.Last = as.double(mazda$Close.Last)
mazda$Open <- substr(mazda$Open, 2, 6)
mazda$Open = as.double(mazda$Open)
mazda$High <- substr(mazda$High, 2, 6)
mazda$High = as.double(mazda$High)
mazda$Low <- substr(mazda$Low, 2, 6)
mazda$Low = as.double(mazda$Low)

isuzu$Date <- as.Date(isuzu$Date, format="%m/%d/%Y")
isuzu$Close.Last <- substr(isuzu$Close.Last, 2, 6)
isuzu$Close.Last = as.double(isuzu$Close.Last)
isuzu$Open <- substr(isuzu$Open, 2, 6)
isuzu$Open = as.double(isuzu$Open)
isuzu$High <- substr(isuzu$High, 2, 6)
isuzu$High = as.double(isuzu$High)
isuzu$Low <- substr(isuzu$Low, 2, 6)
isuzu$Low = as.double(isuzu$Low)